<a href="https://colab.research.google.com/github/SnirNehemia/OU-22961-Deep-Learning/blob/main/mmn11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [78]:
def my_expand_as(A,B):
  # check which dimensions will be broadcasted
  dimension=0
  # while (dimension<len(A.shape) and dimension<len(B.shape) and
  #        (A.shape[-dimension-1] == B.shape[-dimension-1]
  #       or A.shape[-dimension-1] == 1
  #       or B.shape[-dimension-1] == 1)):
  while dimension<len(A.shape) and dimension<len(B.shape) or B.shape[-dimension-1] == 1:
    dimension+=1
    print(1)
  print(f'{dimension=}')
  if dimension==0: # the first dimension doesn't meet the criteria
    raise RuntimeError(f'The size of tensor a ({A.shape[-1]}) must match the size of'
    f'tensor b ({B.shape[-1]}) at non-singleton dimension 1')
  while len(B.shape) > len(A.shape):
    A = torch.stack([A]*B.shape[len(B.shape)-len(A.shape)-1],dim=0)
  C = A
  # print(C)
  # print(C.shape)
  return C

A = torch.ones([2])
B = torch.ones([10,5,2])

Ar = torch.randn([2,1])
Br = torch.randn([2,3,2,1])

# Cr_mine = my_expand_as(Ar.clone(),Br)
Cr_torch = Ar.expand_as(Br)
print(Cr_torch.shape, Cr_mine.shape,sep='\n')

torch.Size([2, 3, 2, 1])
torch.Size([2, 2, 2])


In [57]:
print(Cr_torch)
print(Cr_mine)

tensor([[ 0.7930,  0.7930,  0.7930],
        [-0.6065, -0.6065, -0.6065]])
tensor([[ 0.7930],
        [-0.6065]])


In [46]:
Cr_mine==Cr_torch

tensor([[[[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, True]],

         [[True, True],
          [True, Tru

In [31]:
a = torch.stack([A]*3,dim=0)
print(a.shape)
print(a)

torch.Size([3, 2])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [32]:
a = torch.stack([a]*5,dim=1)
print(a.shape)
print(a)

torch.Size([3, 5, 2])
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
